package ch.hslu.edu.enapp.webshop.erp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-15T13:13:16.216+01:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "Item_Service",
                  wsdlLocation = "file:/C:/Users/marty/Downloads/ItemService.xml",
                  targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
public class ItemService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:microsoft-dynamics-schemas/page/item", "Item_Service");
    public final static QName ItemPort = new QName("urn:microsoft-dynamics-schemas/page/item", "Item_Port");
    static {
        URL url = ItemService.class.getResource("META-INF/wsdl/ItemService.xml");
        if (url == null) {
            url = ItemService.class.getClassLoader().getResource("META-INF/wsdl/ItemService.xml");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(ItemService.class.getName())
                    .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}", "META-INF/wsdl/ItemService.xml");
        }
        WSDL_LOCATION = url;
    }

    public ItemService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ItemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ItemService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ItemService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ItemService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ItemPort
     */
    @WebEndpoint(name = "Item_Port")
    public ItemPort getItemPort() {
        return super.getPort(ItemPort, ItemPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemPort
     */
    @WebEndpoint(name = "Item_Port")
    public ItemPort getItemPort(WebServiceFeature... features) {
        return super.getPort(ItemPort, ItemPort.class, features);
    }

}
